parameters:
    app.rawg_api_key: '%env(RAWG_API_KEY)%'
    youtube_api_key: '%env(YOUTUBE_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\RawgService:
        arguments:
            $apiKey: '%app.rawg_api_key%'

    App\Service\YouTubeService:
        arguments:
            $apiKey: '%youtube_api_key%'
